name: Lint and Test
on: push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php_version}}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        run: composer install --prefer-source --no-progress
      - name: Run test suite
        run: composer run-script ci
      - name: Send mail on failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.CI_MAIL_USERNAME}}
          password: ${{secrets.CI_MAIL_PASSWORD}}
          to: wikidata-ci-status@wikimedia.de
          from: ${{ github.repository }} CI
          subject: CI job failed for ${{ github.repository }}
          html_body: |
            CI workflow ${{ github.workflow }} failed!
            The failed job can be found in <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">here</a>
